[package]
name = "freivalds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
nalgebra = "0.30.0"
ark-ff = "0.3.0"
ark-std = "0.3.0"
ark-bls12-381 = "0.3.0"

